version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/event-management
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   ports:
  #     - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

# volumes:
#   mongodbdata:
