services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb+srv://gaithriharidaswork:iPKab1tqjfFQ0m4F@eventmanagement.ow7rn.mongodb.net/?retryWrites=true&w=majority&appName=EventManagement

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
